Repository Cluting/cluting-frontend, pull requests merged in 2024-12, with the labels that each got.

#98 feat: 지원자 프로세스 기본 세팅
  src/App.tsx
  src/components/applicant/announcement_list/AnnouncementListContainer.tsx
  src/components/applicant/announcement_list/container/AppliedContainer.tsx
  src/components/applicant/announcement_list/container/BookmarkContainer.tsx
  src/components/applicant/announcement_list/container/InProgressContainer.tsx
  src/components/applicant/announcement_list/container/RecentContainer.tsx
  src/components/applicant/announcement_list/detail/AnnouncementListDetailContainer.tsx
  src/components/applicant/announcement_list/detail/container/AnnouncementContainer.tsx
  src/components/applicant/announcement_list/detail/container/DocumentSubmitContainer.tsx
  src/components/applicant/announcement_list/detail/container/InqueryContainer.tsx
  src/components/applicant/application_history/ApplicationHistoryContainer.tsx
  src/components/applicant/application_history/container/FailClubContainer.tsx
  src/components/applicant/application_history/container/PassClubContainer.tsx
  src/components/applicant/application_history/detail/ApplicationHistoryDetailContainer.tsx
  src/components/applicant/application_history/detail/container/MyDocumentContainer.tsx
  src/components/applicant/application_history/detail/container/MyPortfolioContainer.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer.tsx
  src/components/applicant/profile/ApplicantProfileContainer.tsx
  src/components/applicant/profile/profile_container/PortfolioContainer.tsx
  src/components/applicant/profile/profile_container/ProfileContainer.tsx
  src/pages/Applicant/AnnouncementList.tsx
  src/pages/Applicant/AnnouncementListDetail.tsx
  src/pages/Applicant/ApplicantHistory.tsx
  src/pages/Applicant/ApplicantHistoryDetail.tsx
  src/pages/Applicant/ApplicantHome.tsx
  src/pages/Applicant/ApplicantProfile.tsx
Labels: ✨ 작업 완료, ❗확인 요청

#96 feat: 로그인, 회원가입 API 연결 및 로그인 기능 구현
  public/assets/logo/ic-logoIcon-black.svg
  src/App.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/PublicRoute.tsx
  src/components/login/LoginContainer.tsx
  src/components/signup/SignupContainer.tsx
  src/components/signup/SignupDropdown.tsx
  src/components/signup/services/User.ts
  src/constants/recruting.ts
  src/pages/SignUp.tsx
  src/services/AxiosInstance.ts
  src/store/useAuthStore.ts
  src/type/formtype.d.ts
  src/type/storetype.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#95 feat: 5-1. 면접 평가 준비하기 페이지 전체 구현 완료
  package-lock.json
  package.json
  public/assets/ic-reset.svg
  public/assets/ic-todoCheck.svg
  src/components/recruting/_02_prepare/_04/AdminsSchedule.tsx
  src/components/recruting/_02_prepare/_05/ApplicantProfile.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/_02_prepare/_05/InterviewTimeSelector.tsx
  src/components/recruting/_03_document_evaluation/_01/DocumentReviewPrepContainer.tsx
  src/components/recruting/_04_interview_notification/_02/ScheduleAdjustmentContainer.tsx
  src/components/recruting/_05_interview_evaluation/_01/PrepareInterviewEvaluationContainer.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/CommonInterviewQuestionsSection.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/GroupInterviewQuestionsSection.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/IndividualInterviewQuestionsSection.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/InterviewQuestionCountSection.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/button/AddButton.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/dropdown/Dropdown.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/headline/Headline.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/input/CheckboxIcon.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/input/QuestionInput.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/input/QuestionNumberInput.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/list/ApplicantItem.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/list/ApplicantList.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/list/ListHeader.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/modal/AuthorityModal.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/processBar/ProcessBar.tsx
  src/components/recruting/_05_interview_evaluation/_01/sections/tabBar/TabBar.tsx
  src/components/recruting/common/AddAdminDropdown.tsx
  src/components/recruting/common/EvaluationCriteria.tsx
  src/components/recruting/common/RoleSetting.tsx
  src/pages/Recruting/step5/InterviewEvaluation.tsx
  src/store/recruiting/_05_interview_evaluation/questionStore.ts
  src/type/formtype.d.ts
Labels: ❗확인 요청, feature

#104 feat: 5-1. 면접 평가하기 준비하기 페이지 구현
  public/assets/ic-back.svg
  public/assets/ic-toggle.svg
  public/assets/ic-toggleButton-right.svg
  public/assets/logo/ic-logoIcon.svg
  public/assets/logo/ic-logoTitle.svg
  public/interviewAnswerTable.json
  src/App.tsx
  src/components/common/Header.tsx
  src/components/recruting/_03_document_evaluation/_02/list/FitMemberList.tsx
  src/components/recruting/_05_interview_evaluation/_02/InterviewEvaluationContainer.tsx
  src/components/recruting/_05_interview_evaluation/_02/ScheduleTopSection.tsx
  src/components/recruting/_05_interview_evaluation/_02/_01_dayOfInterview/DayOfInterviewContainer.tsx
  src/components/recruting/_05_interview_evaluation/_02/_01_dayOfInterview/InterviewTable.tsx
  src/components/recruting/_05_interview_evaluation/_02/_02_afterInterview/AfterInterviewContainer.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/AnswerRecordContainer.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/CommonQuestions.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/IndividualQuestions.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/PartQuestions.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/Profile.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/interviewees.ts
  src/components/recruting/common/Sidemenu.tsx
  src/pages/Recruting/step5/AnswerRecord.tsx
  tailwind.config.js
Labels: ✨ 작업 완료, ❗확인 요청, feature

#90 feat: 5-2 당일 - 면접 평가하기, 답변 기록 페이지 구현
  public/assets/logo/ic-logo-black.svg
  public/assets/logo/ic-logo.svg
  public/assets/logo/ic-logoIcon.svg
  public/assets/logo/ic-logoTitle-black.svg
  public/assets/logo/ic-logoTitle.svg
  public/interviewAnswerTable.json
  src/App.tsx
  src/components/common/Header.tsx
  src/components/login/LoginContainer.tsx
  src/components/recruting/_05_interview_evaluation/_02/_01_dayOfInterview/InterviewTable.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/AnswerRecordContainer.tsx
  src/components/recruting/_05_interview_evaluation/interview_evaluation_record/InterviewEvaluationRecordContainer.tsx
  src/components/recruting/_05_interview_evaluation/interview_evaluation_record/QuestionAnswer.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/components/recruting/document/UserProfile.tsx
  src/pages/Recruting/document/ApplicantDocument.tsx
  src/pages/Recruting/step5/AnswerRecord.tsx
  src/pages/Recruting/step5/InterviewEvaluationRecord.tsx
Labels: ✨ 작업 완료, ❗확인 요청

#108 feat: 공고 리스트, 나의 기록 구현
  package-lock.json
  package.json
  src/components/applicant/announcement_list/AnnouncementListContainer.tsx
  src/components/applicant/announcement_list/container/AppliedContainer.tsx
  src/components/applicant/announcement_list/container/BookmarkContainer.tsx
  src/components/applicant/announcement_list/container/InProgressContainer.tsx
  src/components/applicant/announcement_list/container/RecentContainer.tsx
  src/components/applicant/application_history/ApplicationHistoryContainer.tsx
  src/components/applicant/application_history/container/FailClubContainer.tsx
  src/components/applicant/application_history/container/PassClubContainer.tsx
  src/components/applicant/application_history/detail/ApplicationHistoryDetailContainer.tsx
  src/components/applicant/application_history/detail/ClubInfo.tsx
  src/components/applicant/application_history/detail/container/MyDocumentContainer.tsx
  src/components/applicant/application_history/detail/container/MyPortfolioContainer.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer/Chart/Chart.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer/Chart/CustomLegend.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer/Chart/RenderCustomizedLabel.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer/CompetitionSection.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer/GradeDistributionSection.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer/RecrutingInfoContainer.tsx
  src/components/applicant/application_history/detail/container/RecrutingInfoContainer/ScoreSection.tsx
  src/components/applicant/application_history/detail/container/UserProfileCard/ApplicationQuestions.tsx
  src/components/applicant/application_history/detail/container/UserProfileCard/MyDocumentContainer.tsx
  src/components/applicant/application_history/detail/container/UserProfileCard/UserProfileCard.tsx
  src/components/recruting/home/ClubCard.tsx
  src/components/recruting/home/ClubCardList.tsx
  src/constants/recruting.ts
  src/type/formtype.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#100 feat: 동아리 및 리크루팅 홈 API 연결
  package-lock.json
  public/assets/home/profile-default.png
  public/assets/ic-notice.svg
  public/assets/ic-profile.svg
  public/assets/ic-search.svg
  public/assets/logo/ic-logo-black.svg
  public/assets/logo/ic-logo.svg
  src/App.css
  src/App.tsx
  src/components/applicant/announcement_list/container/AppliedContainer.tsx
  src/components/applicant/announcement_list/container/BookmarkContainer.tsx
  src/components/applicant/announcement_list/container/InProgressContainer.tsx
  src/components/applicant/announcement_list/container/RecentContainer.tsx
  src/components/applicant/application_history/container/FailClubContainer.tsx
  src/components/applicant/application_history/container/PassClubContainer.tsx
  src/components/club/RegisterClubContainer.tsx
  src/components/club/service/Club.ts
  src/components/club/service/ClubUser.ts
  src/components/club/type/club.d.ts
  src/components/common/AdminProfileDropdown.tsx
  src/components/common/Header.tsx
  src/components/recruting/_02_prepare/TopSection.tsx
  src/components/recruting/_03_document_evaluation/common/TopSection.tsx
  src/components/recruting/common/LoadingSpinner.tsx
  src/components/recruting/home/AddAdmin.tsx
  src/components/recruting/home/MainBanner.tsx
  src/components/recruting/home/_admin/AcceptAdminModal.tsx
  src/components/recruting/home/_admin/AddAdmin.tsx
  src/components/recruting/home/_admin/AddAdminModal.tsx
  src/components/recruting/home/_admin/service/Admin.ts
  src/components/recruting/home/_main/ClubAlignDropdown.tsx
  src/components/recruting/home/_main/ClubCard.tsx
  src/components/recruting/home/_main/ClubCardList.tsx
  src/components/recruting/home/_main/MainBanner.tsx
  src/components/recruting/home/_main/MainCategory.tsx
  src/components/recruting/home/_main/Paging.tsx
  src/components/recruting/home/_main/PopularClub.tsx
  src/components/recruting/home/_start/RecrutingStartModal.tsx
  src/components/signup/UploadClubProfile.tsx
  src/pages/Main.tsx
  src/pages/Recruting/RecrutingHome.tsx
  src/services/AxiosInstance.ts
  src/store/useClubStore.ts
  src/store/useStore.ts
  src/type/formtype.d.ts
  src/type/storetype.d.ts
Labels: ✨ 작업 완료, ❗확인 요청
