Repository Cluting/cluting-frontend, pull requests merged in 2024-11, with the labels that each got.

#21 feat: 메인 홈 구현
  package-lock.json
  package.json
  public/assets/ic-darkdropdown.svg
  public/assets/itTimeLogo.svg
  public/assets/popularClub.svg
  src/App.css
  src/App.tsx
  src/components/recruting/home/ClubAlignDropdown.tsx
  src/components/recruting/home/ClubCard.tsx
  src/components/recruting/home/ClubCardList.tsx
  src/components/recruting/home/MainBanner.tsx
  src/components/recruting/home/MainCategory.tsx
  src/components/recruting/home/Paging.tsx
  src/components/recruting/home/PopularClub.tsx
  src/pages/Main.tsx
  tailwind.config.js
Labels: ✨ 작업 완료

#24 feat: 모집하기 - 공고 작성하기
  package-lock.json
  package.json
  public/assets/ic-logoIcon.svg
  public/assets/ic-logoTitle.svg
  src/App.css
  src/components/common/Header.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContainer.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContent.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementDetails.tsx
  src/components/recruting/common/RecruitmentStep.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/components/signup/RegisterClub.tsx
  src/components/signup/UploadProfile.tsx
  src/hooks/useImageUpload.tsx
  src/pages/Recruting/DocumentEvaluation.tsx
  src/pages/Recruting/FinalSelection.tsx
  src/pages/Recruting/InterviewEvaluation.tsx
  src/pages/Recruting/InterviewNotification.tsx
  src/pages/Recruting/RecrutingHome.tsx
  src/pages/Recruting/RecrutingPlan.tsx
  src/pages/Recruting/RecrutingPrepare.tsx
  src/type/type.d.ts
Labels: ✨ 작업 완료

#27 feat: 모집하기 상단 섹션
  public/assets/ic-next.svg
  public/assets/ic-nextHover.svg
  src/App.tsx
  src/components/recruting/_02_prepare/TopSection.tsx
  src/components/recruting/_02_prepare/_01/SetAcceptanceCountContainer.tsx
  src/components/recruting/_02_prepare/_02/DefineIdealCandidateContainer.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContainer.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContent.tsx
  src/components/recruting/_02_prepare/_04/ScheduleInterviewsContainer.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/common/RecruitmentStep.tsx
  src/components/recruting/home/AddAdmin.tsx
  src/constants/recruting.ts
  src/pages/Recruting/FinalSelection.tsx
  src/pages/Recruting/InterviewNotification.tsx
  src/pages/Recruting/RecrutingPrepare.tsx
  src/pages/Recruting/step1/RecrutingPlan.tsx
  src/pages/Recruting/step2/RecrutingPrepare.tsx
  src/pages/Recruting/step3/DocumentEvaluation.tsx
  src/pages/Recruting/step4/InterviewNotification.tsx
  src/pages/Recruting/step5/InterviewEvaluation.tsx
  src/pages/Recruting/step6/FinalSelection.tsx
  src/store/useStore.ts
  src/type/type.d.ts
Labels: ✨ 작업 완료

#30 feat: 모집하기 - 합격 인원 설정하기
  src/App.css
  src/components/recruting/CompleteButton.tsx
  src/components/recruting/_02_prepare/_01/GroupPassCard.tsx
  src/components/recruting/_02_prepare/_01/GroupPassCount.tsx
  src/components/recruting/_02_prepare/_01/NumberSpinner.tsx
  src/components/recruting/_02_prepare/_01/SetAcceptanceCountContainer.tsx
  src/constants/recruting.ts
  src/type/type.d.ts
Labels: ✨ 작업 완료

#33 feat: 캘린더 구현
  package-lock.json
  package.json
  public/assets/ic-dateList.svg
  public/index.html
  src/App.css
  src/components/recruting/_02_prepare/TopSection.tsx
  src/components/recruting/common/RecruitmentStep.tsx
  src/components/recruting/home/_calender/RecrutingCalender.css
  src/components/recruting/home/_calender/RecrutingCalender.tsx
  src/components/recruting/home/_calender/RecrutingPlanCalender.tsx
  src/components/recruting/home/_todo/TodoInsert.js
  src/components/recruting/home/_todo/TodoList.js
  src/components/recruting/home/_todo/TodoListItem.js
  src/components/recruting/home/_todo/TodoTemplate.js
  src/pages/Recruting/RecrutingHome.tsx
  tailwind.config.js
Labels: ✨ 작업 완료

#36 feat: 지원자 그룹짓기 구현
  public/assets/ic-addMain.svg
  public/assets/ic-addWhite.svg
  public/assets/ic-minusCircle.svg
  public/assets/ic-noticeCircle.svg
  src/components/recruting/_02_prepare/TopSection.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContainer.tsx
  src/components/recruting/common/RecruitmentStep.tsx
  src/components/recruting/home/GroupCreate.tsx
  src/components/recruting/home/_calender/RecrutingCalender.tsx
  src/constants/recruting.ts
  src/pages/Recruting/RecrutingHome.tsx
  src/pages/Recruting/step1/RecrutingPlan.tsx
  src/store/useStore.ts
  src/type/type.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#39 feat: 모집 준비 단계 역할 분담 컴포넌트
  package-lock.json
  src/components/recruting/_01_plan/AddAdminDropdown.tsx
  src/components/recruting/_01_plan/PrepareStepRoles.tsx
  src/constants/recruting.ts
  src/pages/Recruting/step1/RecrutingPlan.tsx
  src/type/type.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#31 feat: 회원가입 구현
  package-lock.json
  package.json
  public/assets/logo/ic-logo-black.svg
  public/assets/logo/ic-logoIcon-black.svg
  public/assets/logo/ic-logoIcon.svg
  public/assets/logo/ic-logoTitle-black.svg
  public/assets/logo/ic-logoTitle.svg
  public/assets/social/ic-google.svg
  public/assets/social/ic-kakao.svg
  public/assets/social/ic-naver.svg
  src/App.css
  src/App.tsx
  src/components/common/AdminProfileDropdown.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/RegisterClubContainer.tsx
  src/components/login/LoginContainer.tsx
  src/components/recruting/home/RecrutingStartModal.tsx
  src/components/signup/SignupContainer.tsx
  src/components/signup/SignupDropdown.tsx
  src/components/signup/TermsAgreement.tsx
  src/constants/recruting.ts
  src/pages/Login.tsx
  src/pages/RegisterClub.tsx
  src/pages/SignUp.tsx
  src/type/type.d.ts
Labels: ✨ 작업 완료

#34 feat: 모집하기 - 인재상 구축하기 구현
  package-lock.json
  package.json
  src/App.css
  src/components/recruting/_02_prepare/_01/GroupPassCard.tsx
  src/components/recruting/_02_prepare/_01/SetAcceptanceCountContainer.tsx
  src/components/recruting/_02_prepare/_02/CommonIdeal.tsx
  src/components/recruting/_02_prepare/_02/DefineIdealCandidateContainer.tsx
  src/components/recruting/_02_prepare/_02/GroupIdeal.tsx
  src/type/type.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#40 feat: 계획하기- 리크루팅 일정 설정 (캘린더)
  package-lock.json
  package.json
  public/assets/ic-recruitingList-01.svg
  public/assets/ic-recruitingList-02.svg
  public/assets/ic-recruitingList-03.svg
  public/assets/ic-recruitingList-04.svg
  public/assets/ic-sidemenu-home.svg
  public/assets/ic-sidemenu-notice.svg
  public/assets/ic-sidemenu-setting.svg
  public/assets/ic-step-01.svg
  public/assets/ic-step-02.svg
  public/assets/ic-step-03.svg
  public/assets/ic-step-04.svg
  public/assets/ic-step-05.svg
  public/assets/ic-step-06.svg
  src/components/common/AdminProfileDropdown.tsx
  src/components/recruting/_01_plan/AddAdminDropdown.tsx
  src/components/recruting/_02_prepare/TopSection.tsx
  src/components/recruting/_02_prepare/_01/RecruitingCalenderPicker.tsx
  src/components/recruting/_02_prepare/_02/GroupIdeal.tsx
  src/components/recruting/common/RecruitmentStep.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/components/recruting/home/AddAdmin.tsx
  src/components/recruting/home/AddAdminModal.tsx
  src/components/recruting/home/ClubAlignDropdown.tsx
  src/components/recruting/home/RecruitingCalendar.tsx
  src/components/recruting/home/_calender/RecrutingCalender.css
  src/components/recruting/home/_calender/RecrutingCalender.tsx
  src/components/recruting/home/_calender/RecrutingPlanCalender.tsx
  src/components/signup/SignupContainer.tsx
  src/components/signup/SignupDropdown.tsx
  src/constants/recruting.ts
  src/pages/Recruting/RecrutingHome.tsx
  src/pages/Recruting/step1/RecrutingPlan.tsx
  src/pages/Recruting/step2/RecrutingPrepare.tsx
  src/style/calendar.css
  tailwind.config.js
Labels: ✏️ 작업 중

#42 feat: 모집하기 - 면접관 일정 확인 컴포넌트
  public/assets/ic-nextDate.svg
  public/assets/ic-prevDate.svg
  src/components/recruting/_01_plan/PrepareStepRoles.tsx
  src/components/recruting/_02_prepare/_04/AdminsSchedule.tsx
  src/components/recruting/_02_prepare/_04/ScheduleInterviewsContainer.tsx
  src/type/type.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#44 feat: 2-5 지원서 폼 제작
  package-lock.json
  package.json
  public/assets/ic-descriptive.svg
  public/assets/ic-mainColorPlus.svg
  public/assets/ic-multiple.svg
  public/assets/ic-plus.svg
  public/assets/ic-questionMinus.svg
  public/assets/ic-whiteColorPlus.svg
  src/App.css
  src/components/recruting/_02_prepare/_04/AdminsSchedule.tsx
  src/components/recruting/_02_prepare/_05/ApplicantProfile.tsx
  src/components/recruting/_02_prepare/_05/ApplicationGroup.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/_02_prepare/_05/GroupQuestion.tsx
  src/type/type.d.ts
Labels: ✨ 작업 완료, ✏️ 작업 중

#45 feat: 면접 일정 선택
  src/App.css
  src/components/recruting/_02_prepare/_01/RecruitingCalenderPicker.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementDetails.tsx
  src/components/recruting/_02_prepare/_04/AdminsSchedule.tsx
  src/components/recruting/_02_prepare/_04/CustomSelect.tsx
  src/components/recruting/_02_prepare/_04/InterviewAvailableTime.tsx
  src/components/recruting/_02_prepare/_04/InterviewFormat.tsx
  src/components/recruting/_02_prepare/_04/InterviewTime.tsx
  src/components/recruting/_02_prepare/_04/ScheduleInterviewsContainer.tsx
  src/components/recruting/_02_prepare/_04/TimeSlot.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/index.css
  src/store/useStore.ts
  src/type/formtype.d.ts
  src/type/storetype.d.ts
Labels: ✨ 작업 완료

#52 refactor: 2단계 수정
  package-lock.json
  package.json
  public/assets/ic-activityDay.svg
  public/assets/ic-activityTime.svg
  public/assets/ic-clubFee.svg
  public/assets/ic-imageUpload.svg
  public/assets/ic-profile.svg
  public/assets/ic-recruitsCount.svg
  public/assets/ic-topSection-checked.svg
  src/App.css
  src/components/common/AdminProfileDropdown.tsx
  src/components/common/Header.tsx
  src/components/recruting/_01_plan/AddAdminDropdown.tsx
  src/components/recruting/_01_plan/PrepareStepRoles.tsx
  src/components/recruting/_02_prepare/TopSection.tsx
  src/components/recruting/_02_prepare/_01/GroupCreate.tsx
  src/components/recruting/_02_prepare/_01/GroupPassCard.tsx
  src/components/recruting/_02_prepare/_01/GroupPassCount.tsx
  src/components/recruting/_02_prepare/_01/RecruitingCalenderPicker.tsx
  src/components/recruting/_02_prepare/_01/SetAcceptanceCountContainer.tsx
  src/components/recruting/_02_prepare/_02/CommonIdeal.tsx
  src/components/recruting/_02_prepare/_02/DefineIdealCandidateContainer.tsx
  src/components/recruting/_02_prepare/_02/GroupIdeal.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContainer.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContent.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementDetails.tsx
  src/components/recruting/_02_prepare/_04/CustomSelect.tsx
  src/components/recruting/_02_prepare/_04/InterviewAvailableTime.tsx
  src/components/recruting/_02_prepare/_04/ScheduleInterviewsContainer.tsx
  src/components/recruting/_02_prepare/_04/TimeSlot.tsx
  src/components/recruting/_02_prepare/_05/ApplicationGroup.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/_02_prepare/_05/GroupQuestion.tsx
  src/components/recruting/_03_document_evaluation/_01/DocumentReviewPrepContainer.tsx
  src/components/recruting/_03_document_evaluation/common/TopSection.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/components/recruting/common/StepCompleteModal.tsx
  src/components/recruting/home/AddAdmin.tsx
  src/components/recruting/home/ClubAlignDropdown.tsx
  src/components/recruting/home/RecruitingCalendar.tsx
  src/constants/recruting.ts
  src/index.css
  src/pages/Recruting/RecrutingHome.tsx
  src/pages/Recruting/step1/RecrutingPlan.tsx
  src/pages/Recruting/step2/RecrutingPrepare.tsx
  src/pages/Recruting/step3/DocumentEvaluation.tsx
  src/pages/Recruting/step4/InterviewNotification.tsx
  src/pages/Recruting/step5/InterviewEvaluation.tsx
  src/pages/Recruting/step6/FinalSelection.tsx
  src/store/useStore.ts
  src/style/calendar.css
  src/type/formtype.d.ts
  src/type/storetype.d.ts
  tailwind.config.js
Labels: ✨ 작업 완료

#69 feat: 4-1 지원자 합불 결과 구현
  package-lock.json
  package.json
  public/failApplicant.json
  public/passApplicant.json
  src/components/recruting/_04_interview_notification/_01/ApplicantStatusContainer.tsx
  src/components/recruting/_04_interview_notification/_01/FailList.tsx
  src/components/recruting/_04_interview_notification/_01/PassList.tsx
  src/components/recruting/_04_interview_notification/_02/ScheduleAdjustmentContainer.tsx
  src/components/recruting/_04_interview_notification/_03/ResultMessageContainer.tsx
  src/components/recruting/_04_interview_notification/common/TopSection.tsx
  src/components/signup/SignupContainer.tsx
  src/index.tsx
  src/pages/Recruting/step4/InterviewNotification.tsx
  src/services/AxiosInstance.ts
  src/services/User.ts
  src/store/useStore.ts
  src/type/formtype.d.ts
  src/type/storetype.d.ts
  src/type/type.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#73 feat: 4-3 합불 메시지 작성 구현
  public/assets/ic-ideal.svg
  public/assets/messageExample.png
  src/components/recruting/_03_document_evaluation/evaluation/AdminEvaluationWindow.tsx
  src/components/recruting/_03_document_evaluation/evaluation/EvaluationCard.tsx
  src/components/recruting/_04_interview_notification/_03/PreviewModal.tsx
  src/components/recruting/_04_interview_notification/_03/ResultMessageContainer.tsx
  src/components/recruting/common/StepCompleteModal.tsx
  src/type/formtype.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#75 feat: 5,6단계 페이지 컨테이너 및 TopSection 세팅
  src/App.tsx
  src/components/recruting/_04_interview_notification/_03/ResultMessageContainer.tsx
  src/components/recruting/_05_interview_evaluation/_01/PrepareInterviewEvaluationContainer.tsx
  src/components/recruting/_05_interview_evaluation/_02/InterviewEvaluationContainer.tsx
  src/components/recruting/_05_interview_evaluation/common/TopSection.tsx
  src/components/recruting/_06_final_selection/_01/ApplicantStatusContainer.tsx
  src/components/recruting/_06_final_selection/_01/FailList.tsx
  src/components/recruting/_06_final_selection/_01/PassList.tsx
  src/components/recruting/_06_final_selection/_02/ResultMessageContainer.tsx
  src/components/recruting/_06_final_selection/common/TopSection.tsx
  src/pages/Recruting/step5/InterviewEvaluation.tsx
  src/pages/Recruting/step6/FinalSelection.tsx
  src/store/useStore.ts
Labels: ✨ 작업 완료, ❗확인 요청

#82 feat: 개별 질문 작성 페이지 구현
  src/App.tsx
  src/components/recruting/_05_interview_evaluation/individual_question/IndividualQuestionWindow.tsx
  src/components/recruting/_05_interview_evaluation/individual_question/Question.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/components/recruting/document/ApplicationQuestion.tsx
  src/components/recruting/document/Portfolio.tsx
  src/components/recruting/document/PortfolioPDF.tsx
  src/components/recruting/document/UserProfile.tsx
  src/pages/Recruting/document/ApplicantDocument.tsx
Labels: ✨ 작업 완료, ❗확인 요청

#85 refactor: 4-1, 4-3 구현 및 리팩토링
  .gitignore
  public/assets/messageExample.jpg
  public/assets/messageExample.png
  src/components/recruting/_04_interview_notification/_01/AlignDropdown.tsx
  src/components/recruting/_04_interview_notification/_01/ApplicantStatusContainer.tsx
  src/components/recruting/_04_interview_notification/_01/FailList.tsx
  src/components/recruting/_04_interview_notification/_01/FilterDropdown.tsx
  src/components/recruting/_04_interview_notification/_01/PassList.tsx
  src/components/recruting/_04_interview_notification/_03/PreviewModal.tsx
  src/components/recruting/_04_interview_notification/_03/ResultMessageContainer.tsx
  src/components/recruting/common/StepCompleteModal.tsx
Labels: ✨ 작업 완료, ❗확인 요청

#87 feat: 6-1 지원자 합불 결과 구현
  src/components/recruting/_06_final_selection/_01/ApplicantStatusContainer.tsx
  src/components/recruting/_06_final_selection/_01/FailList.tsx
  src/components/recruting/_06_final_selection/_01/PassList.tsx
Labels: ✨ 작업 완료, ❗확인 요청

#89 feat: 6-2 합불 메시지 전송 구현
  public/assets/messageExample-6-2.jpg
  src/components/recruting/_06_final_selection/_02/PreviewModal.tsx
  src/components/recruting/_06_final_selection/_02/ResultMessageContainer.tsx
Labels: ✨ 작업 완료, ❗확인 요청

#83 feat: 3-2 서류 평가하기
  src/components/recruting/_03_document_evaluation/_02/DocumentReviewContainer.tsx
  src/components/recruting/_03_document_evaluation/_02/common/DropDown.tsx
  src/components/recruting/_03_document_evaluation/_02/common/EvalProcessBar.tsx
  src/components/recruting/_03_document_evaluation/_02/list/FitMemberList.tsx
  src/components/recruting/_03_document_evaluation/_02/list/WideMemberList.tsx
  src/components/recruting/_03_document_evaluation/_02/list/button/Button.tsx
  src/components/recruting/_03_document_evaluation/_02/list/types/buttonTypes.ts
  src/components/recruting/_03_document_evaluation/_02/step/AfterEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/BeforeEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/CompletedEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/DuringEvaluation.tsx
  src/pages/Recruting/step3/DocumentEvaluation.tsx
Labels: ✏️ 작업 중, feature

#71 feat: 3-1 서류 평가 준비하기
  public/assets/ic-add.svg
  public/assets/ic-mainColorPlus.svg
  src/App.css
  src/assets/ic-plus.svg
  src/components/recruting/_01_plan/AddAdminDropdown.tsx
  src/components/recruting/_01_plan/PrepareStepRoles.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/_03_document_evaluation/_01/AddAdminDropdown.tsx
  src/components/recruting/_03_document_evaluation/_01/DocumentReviewPrepContainer.tsx
  src/pages/LandingPage.tsx
  src/pages/Recruting/step3/DocumentEvaluation.tsx
  src/type/formtype.d.ts
Labels: ✨ 작업 완료, ❗확인 요청
