Repository Cluting/cluting-frontend, pull requests merged in 2025-01, with the labels that each got.

#120 feat:운영진 초대 프로세스 api 연결 및 임시 로그아웃 구현
  src/App.tsx
  src/components/common/Header.tsx
  src/components/login/LoginContainer.tsx
  src/components/recruting/home/_admin/AcceptAdminModal.tsx
  src/components/recruting/home/_admin/AddAdminModal.tsx
  src/components/recruting/home/_admin/AdminInvite.tsx
  src/components/recruting/home/_admin/service/Admin.ts
  src/pages/Recruting/RecrutingHome.tsx
  src/services/AxiosInstance.ts
Labels: ✨ 작업 완료, ❗확인 요청

#115 feat: 지원자 프로세스 사이드 메뉴 구현
  public/assets/sidemenu/ic-announcementList-main.svg
  public/assets/sidemenu/ic-announcementList.svg
  public/assets/sidemenu/ic-myHistory-main.svg
  public/assets/sidemenu/ic-myHistory.svg
  public/assets/sidemenu/ic-saveProfile-main.svg
  public/assets/sidemenu/ic-saveProfile.svg
  src/components/applicant/common/Sidemenu.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/pages/Applicant/AnnouncementList.tsx
  src/pages/Applicant/AnnouncementListDetail.tsx
  src/pages/Applicant/ApplicantHistory.tsx
  src/pages/Applicant/ApplicantHistoryDetail.tsx
  src/pages/Applicant/ApplicantHome.tsx
  src/pages/Applicant/ApplicantProfile.tsx
Labels: ✨ 작업 완료, ❗확인 요청

#117 feat: 리크루팅 1단계 계획하기 api 연결
  src/components/club/RegisterClubContainer.tsx
  src/components/recruting/_01_plan/AddAdminDropdown.tsx
  src/components/recruting/_01_plan/PrepareStepRoles.tsx
  src/components/recruting/_01_plan/RecruitingPlanContainer.tsx
  src/components/recruting/_01_plan/service/Prep.ts
  src/components/recruting/_01_plan/type/Prep.ts
  src/components/recruting/_02_prepare/_01/GroupCreate.tsx
  src/components/recruting/_02_prepare/_01/RecruitingCalenderPicker.tsx
  src/components/recruting/common/AddAdminDropdown.tsx
  src/components/recruting/common/RoleSetting.tsx
  src/constants/recruting.ts
  src/pages/Recruting/step1/RecrutingPlan.tsx
  src/type/formtype.d.ts
  src/type/type.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#103 feat: 2-3 api 연결
  src/components/recruting/_02_prepare/_03/AnnouncementContainer.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContent.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementDetails.tsx
  src/components/recruting/_02_prepare/service/Step2.ts
  src/services/AxiosInstance.ts
  src/type/formtype.d.ts
Labels: ✨ 작업 완료, ❗확인 요청

#124 feat: 3단계 구현 및 API 연결
  src/App.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/_03_document_evaluation/_01/DocumentReviewPrepContainer.tsx
  src/components/recruting/_03_document_evaluation/_02/DocumentReviewContainer.tsx
  src/components/recruting/_03_document_evaluation/_02/common/DecisionPassFailModal.tsx
  src/components/recruting/_03_document_evaluation/_02/list/FitMemberList.tsx
  src/components/recruting/_03_document_evaluation/_02/list/WideMemberList.tsx
  src/components/recruting/_03_document_evaluation/_02/list/button/Button.tsx
  src/components/recruting/_03_document_evaluation/_02/list/types/buttonTypes.ts
  src/components/recruting/_03_document_evaluation/_02/step/AfterEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/BeforeEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/CompletedEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/DuringEvaluation.tsx
  src/components/recruting/_03_document_evaluation/common/TopSection.tsx
  src/components/recruting/_03_document_evaluation/evaluation/AdminEvaluationWindow.tsx
  src/components/recruting/_03_document_evaluation/evaluation/ClubIdealList.tsx
  src/components/recruting/_03_document_evaluation/evaluation/EvaluationCard.tsx
  src/components/recruting/_03_document_evaluation/service/Step3.ts
  src/components/recruting/_03_document_evaluation/type/step3.d.ts
  src/components/recruting/_05_interview_evaluation/common/TopSection.tsx
  src/components/recruting/common/EvaluationCriteria.tsx
  src/components/recruting/common/RoleSetting.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/components/recruting/document/UserProfile.tsx
  src/components/recruting/home/RecruitingCalendar.tsx
  src/constants/recruting.ts
  src/pages/Recruting/document/ApplicantDocument.tsx
  src/pages/Recruting/step3/DocumentEval.tsx
  src/pages/Recruting/step3/DocumentEvaluation.tsx
  src/pages/Recruting/step3/DocumentPrep.tsx
  src/pages/Recruting/step3/document/ApplicantDocument.tsx
  src/pages/Recruting/step5/InterviewEval.tsx
  src/pages/Recruting/step5/InterviewPrep.tsx
  src/services/AxiosInstance.ts
  src/store/useEvaluationStore.ts
  src/store/useStore.ts
  src/type/evaluationtype.d.ts
Labels: ✏️ 작업 중

#122 feat: 2-4 API 연결
  src/components/recruting/_02_prepare/_04/AdminsSchedule.tsx
  src/components/recruting/_02_prepare/_04/InterviewAvailableTime.tsx
  src/components/recruting/_02_prepare/_04/InterviewFormat.tsx
  src/components/recruting/_02_prepare/_04/InterviewTime.tsx
  src/components/recruting/_02_prepare/_04/ScheduleInterviewsContainer.tsx
  src/components/recruting/_02_prepare/_04/TimeSlot.tsx
  src/components/recruting/_02_prepare/_04/type/2-4.d.ts
  src/components/recruting/_02_prepare/service/Step2.ts
  src/constants/recruting.ts
  src/store/useStore.ts
  src/type/storetype.d.ts
Labels: ✏️ 작업 중

#130 feat: 4단계 API 연결
  src/components/recruting/_04_interview_notification/_01/FilterDropdown.tsx
  src/components/recruting/_04_interview_notification/service/Step4.ts
Labels: ✏️ 작업 중

#144 🔧 fix: 은혜님 개별질문 리스트, 전역상태 데이터 일치
  src/components/recruting/_05_interview_evaluation/_01/sections/IndividualInterviewQuestionsSection.tsx
  src/store/useEvaluationStore.ts
Labels: ✨ 작업 완료

#146 hotfix: 유저테스트 수정사항 수정
  src/App.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/_03_document_evaluation/_02/list/FitMemberList.tsx
  src/components/recruting/_03_document_evaluation/_02/list/WideMemberList.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/AnswerRecordContainer.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/CommonQuestions.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/PartQuestions.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/interviewees.ts
  src/components/recruting/_05_interview_evaluation/interview_evaluation_record/InterviewEvaluationRecordContainer.tsx
Labels: ✨ 작업 완료

#140 feat: 메인 홈 API 연결
  public/assets/home/main/defaultClub.svg
  src/components/recruting/home/_main/ClubAlignDropdown.tsx
  src/components/recruting/home/_main/ClubCard.tsx
  src/components/recruting/home/_main/ClubCardList.tsx
  src/components/recruting/home/_main/MainBanner.tsx
  src/components/recruting/home/_main/MainCategory.tsx
  src/components/recruting/home/_main/MainContainer.tsx
  src/components/recruting/home/_main/Paging.tsx
  src/components/recruting/home/_main/dummyData.ts
  src/components/recruting/home/_main/service/mainClub.ts
  src/components/recruting/home/_main/type/mainClub.d.ts
  src/pages/Main.tsx
  src/type/formtype.d.ts
Labels: ✨ 작업 완료

#138 feat: 운영진 프로세스 api 통합
  public/index.html
  src/components/applicant/common/Sidemenu.tsx
  src/components/common/AdminProfileDropdown.tsx
  src/components/common/Header.tsx
  src/components/recruting/_04_interview_notification/_01/AlignDropdown.tsx
  src/components/recruting/_04_interview_notification/_01/ApplicantStatusContainer.tsx
  src/components/recruting/_04_interview_notification/_01/FailList.tsx
  src/components/recruting/_04_interview_notification/_01/PassList.tsx
  src/components/recruting/_04_interview_notification/_03/PreviewModal.tsx
  src/components/recruting/_04_interview_notification/_03/ResultMessageContainer.tsx
  src/components/recruting/_04_interview_notification/service/Step4.ts
  src/components/recruting/_06_final_selection/_01/ApplicantStatusContainer.tsx
  src/components/recruting/_06_final_selection/_01/FailList.tsx
  src/components/recruting/_06_final_selection/_01/PassList.tsx
  src/components/recruting/_06_final_selection/_02/PreviewModal.tsx
  src/components/recruting/_06_final_selection/_02/ResultMessageContainer.tsx
  src/components/recruting/_06_final_selection/service/Step6.ts
  src/components/recruting/common/AddAdminDropdown.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/components/recruting/home/_start/RecrutingStartModal.tsx
  src/components/recruting/home/_todo/TodoTemplate.tsx
  src/components/recruting/home/_todo/service/todo.ts
  src/pages/Applicant/AnnouncementList.tsx
  src/pages/Applicant/AnnouncementListDetail.tsx
  src/pages/Applicant/ApplicantHistory.tsx
  src/pages/Applicant/ApplicantHistoryDetail.tsx
  src/pages/Recruting/RecrutingHome.tsx
  src/pages/Recruting/step2/RecrutingPrepare.tsx
  src/pages/Recruting/step4/InterviewNotification.tsx
  src/pages/Recruting/step6/FinalSelection.tsx
  src/store/useStore.ts
  src/type/storetype.d.ts
  src/type/type.d.ts
Labels: ✏️ 작업 중

#157 156 hotfix 시연영상 전 수정사항
  public/index.html
  src/components/recruting/_02_prepare/_01/SetAcceptanceCountContainer.tsx
  src/components/recruting/_02_prepare/_01/service/Step1.ts
  src/components/recruting/_02_prepare/_03/AnnouncementContainer.tsx
  src/components/recruting/_02_prepare/_04/AdminsSchedule.tsx
  src/components/recruting/_03_document_evaluation/_01/DocumentReviewPrepContainer.tsx
  src/components/recruting/common/EvaluationCriteria.tsx
  src/components/recruting/common/RoleSetting.tsx
Labels: ✨ 작업 완료

#159 hotfix: 운영진 프로세스 시연영상 플로우 구현
  src/App.tsx
  src/components/recruting/_01_plan/PrepareStepRoles.tsx
  src/components/recruting/_01_plan/RecruitingPlanContainer.tsx
  src/components/recruting/_01_plan/service/Prep.ts
  src/components/recruting/_01_plan/type/Prep.d.ts
  src/components/recruting/_02_prepare/_01/RecruitingCalenderPicker.tsx
  src/components/recruting/_02_prepare/_01/SetAcceptanceCountContainer.tsx
  src/components/recruting/_02_prepare/_02/DefineIdealCandidateContainer.tsx
  src/components/recruting/_02_prepare/_03/AnnouncementContainer.tsx
  src/components/recruting/_02_prepare/_05/CreateApplicationFormContainer.tsx
  src/components/recruting/_02_prepare/service/Step2.ts
  src/components/recruting/_03_document_evaluation/_02/list/FitMemberList.tsx
  src/components/recruting/_03_document_evaluation/_02/step/BeforeEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/CompletedEvaluation.tsx
  src/components/recruting/_03_document_evaluation/_02/step/DuringEvaluation.tsx
  src/components/recruting/_03_document_evaluation/type/step3.d.ts
  src/components/recruting/_04_interview_notification/_01/FailList.tsx
  src/components/recruting/_04_interview_notification/_01/PassList.tsx
  src/components/recruting/_04_interview_notification/_03/PreviewModal.tsx
  src/components/recruting/_05_interview_evaluation/_02/ScheduleTopSection.tsx
  src/components/recruting/_05_interview_evaluation/_02/_01_dayOfInterview/DayOfInterviewContainer.tsx
  src/components/recruting/_05_interview_evaluation/_02/_02_afterInterview/AfterInterviewContainer.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/AnswerRecordContainer.tsx
  src/components/recruting/_05_interview_evaluation/common/TopSection.tsx
  src/components/recruting/_05_interview_evaluation/interview_evaluation_record/InterviewEvaluationRecordContainer.tsx
  src/components/recruting/_06_final_selection/_01/FailList.tsx
  src/components/recruting/_06_final_selection/_01/PassList.tsx
  src/components/recruting/_06_final_selection/_02/PreviewModal.tsx
  src/components/recruting/common/Sidemenu.tsx
  src/constants/recruting.ts
  src/store/useStore.ts
  src/type/storetype.d.ts
Labels: ✏️ 작업 중

#139 feat: 4-2 구현 및 API 연결
  public/index.html
  src/components/recruting/_04_interview_notification/_02/ApplicantButton.tsx
  src/components/recruting/_04_interview_notification/_02/DateNavigator.tsx
  src/components/recruting/_04_interview_notification/_02/GroupTabs.tsx
  src/components/recruting/_04_interview_notification/_02/ScheduleAdjustmentContainer.tsx
  src/components/recruting/_04_interview_notification/_02/ScheduleGrid.tsx
  src/components/recruting/_04_interview_notification/_02/TimeSlot.tsx
  src/components/recruting/_04_interview_notification/_02/constants/interview.ts
  src/components/recruting/_04_interview_notification/_02/service/ScheduleAdjustment.ts
  src/components/recruting/_04_interview_notification/_02/type/types.d.ts
  src/components/recruting/_04_interview_notification/_02/utils/date.ts
  src/components/recruting/_04_interview_notification/_02/utils/generateScheduleData.ts
  src/components/recruting/_04_interview_notification/_02/utils/schedule.ts
  src/components/recruting/_04_interview_notification/_02/utils/validators.ts
Labels: ✏️ 작업 중

#167 hotfix:계획하기 3,5단계 api 수정사항 반영
  public/assets/ic-send-chat.svg
  public/assets/inquery/inquery-1.png
  public/assets/inquery/inquery-2.png
  public/assets/inquery/inquery-3.png
  public/assets/inquery/inquery-4.png
  public/assets/inquery/inquery-5.png
  public/assets/inquery/inquery-6.png
  public/assets/inquery/inquery-7.png
  public/assets/inquery/next.svg
  public/assets/inquery/previous.svg
  public/itstime.png
  src/components/applicant/announcement_list/detail/AnnouncementListDetailContainer.tsx
  src/components/applicant/announcement_list/detail/container/InqueryContainer.tsx
  src/components/applicant/announcement_list/detail/inquery_highlight/InqueryContainer.tsx
  src/components/applicant/announcement_list/detail/inquery_highlight/components/Chatting.tsx
  src/components/applicant/announcement_list/detail/inquery_highlight/components/Highlight.tsx
  src/components/applicant/home/ApplicantCalendar.tsx
  src/components/applicant/home/ApplicantHomeContainer.tsx
  src/components/applicant/home/ApplicationStatus.tsx
  src/components/applicant/profile/ApplicantProfileContainer.tsx
  src/components/recruting/_01_plan/AddAdminDropdown.tsx
  src/components/recruting/_01_plan/PrepareStepRoles.tsx
  src/components/recruting/_01_plan/RecruitingPlanContainer.tsx
  src/components/recruting/_01_plan/service/Prep.ts
  src/components/recruting/_01_plan/type/Prep.d.ts
  src/components/recruting/_02_prepare/_01/RecruitingCalenderPicker.tsx
  src/components/recruting/_02_prepare/_04/InterviewAvailableTime.tsx
  src/components/recruting/_02_prepare/_04/TimeSlot.tsx
  src/components/recruting/_03_document_evaluation/service/Step3.ts
  src/components/recruting/_05_interview_evaluation/_02/_02_afterInterview/step/AfterEvaluation.tsx
  src/components/recruting/_05_interview_evaluation/_02/_02_afterInterview/step/BeforeEvaluation.tsx
  src/components/recruting/_05_interview_evaluation/_02/_02_afterInterview/step/DuringEvaluation.tsx
  src/components/recruting/_05_interview_evaluation/answer_record/AnswerRecordContainer.tsx
  src/components/recruting/_05_interview_evaluation/service/Step5.ts
  src/components/recruting/_05_interview_evaluation/type/step5.d.ts
  src/components/recruting/home/RecruitingCalendar.tsx
  src/components/recruting/home/_admin/AddAdmin.tsx
  src/components/recruting/home/_todo/service/todo.ts
  src/pages/Applicant/AnnouncementListDetail.tsx
  src/store/useStore.ts
  src/type/storetype.d.ts
Labels: ✨ 작업 완료

#173 hotfix: 최종 발표 수정사항 수정
  src/components/recruting/_03_document_evaluation/_02/step/CompletedEvaluation.tsx
  src/components/recruting/_03_document_evaluation/evaluation/AdminEvaluationWindow.tsx
  src/components/recruting/home/_todo/service/todo.ts
Labels: ✨ 작업 완료

#178 feat: 랜딩페이지 바뀐 버전 구현
  public/assets/landing/applicant-card.png
  public/assets/landing/bubble-01.png
  public/assets/landing/bubble-02.png
  public/assets/landing/frame01.png
  public/assets/landing/ic-club-list.svg
  public/assets/landing/landing-logo.svg
  public/assets/landing/process-bubble.png
  public/assets/landing/process.png
  public/assets/landing/section1-bottom.svg
  public/assets/landing/section1-img.svg
  public/assets/landing/section2-img1.svg
  public/assets/landing/section2-img2.svg
  public/assets/landing/section3-admin.png
  public/assets/landing/section5.png
  public/assets/landing/star.svg
  src/App.tsx
  src/components/applicant/announcement_list/detail/AnnouncementListDetailContainer.tsx
  src/components/club/RegisterClubContainer.tsx
  src/components/common/Header.tsx
  src/components/login/LoginContainer.tsx
  src/components/login/PublicRoute.tsx
  src/components/recruting/home/_admin/AdminInvite.tsx
  src/index.css
  src/pages/LandingPage.tsx
  tailwind.config.js
Labels: ✨ 작업 완료
